### PR TITLE
solve navbar problem and make it fixed

### LINKED ISSUE #343: [Bug] : Navbar width is not as per screen
@Rajan-Barnwal 

check this out,

image

the navigation is not looking good

### PR DESCRIPTION
**Pull request by dhruv8433**
@Rajan-Barnwal 

## description: 

[Bug] : Navbar width is not as per screen #343

close #343

## Screenshorts

image

image

### CODE REVIEW

**Comment by dhruv8433** [comment]
@Rajan-Barnwal 

please check this and merge it

**Comment by dhruv8433** [comment]
@Rajan-Barnwal

please check this and merge it
and add level label

**Comment by dhruv8433** [comment]
@Rajan-Barnwal

please response !!!

please check this and merge it
and add level label

**Comment by sanjay-kv** [comment]
@Poonam-Kashyap12 @Ishmeetkaur36 

Kindly look into his PR, if any issue let him know.

**Pull request closed without merging**
