### PR TITLE
navbar

### PR DESCRIPTION
**Pull request by puneet426**
closes :- #313 and #323 

https://github.com/Rajan-Barnwal/jobproject/assets/168094736/b6ddd1be-32c1-4d3a-a1fe-1b93348f8cd1

a new navbar idea

### CODE REVIEW

**Comment by puneet426** [comment]
hello @Rajan-Barnwal i resolve this issue please assign me under GSSoC 2024 and merge it

**Comment by puneet426** [comment]
hello @Rajan-Barnwal please add level like level 1, level2 and merge and close this issue

**Comment by puneet426** [comment]
@Rajan-Barnwal i done it 3 day before and upto now you are not responding

**Comment by pallabisneha** [comment]
can you please labeled the issue ?

**Comment by puneet426** [comment]
@pallabisneha the project owner level the issue

**Comment by puneet426** [comment]
@Rajan-Barnwal please merge it and closes two issue

**Comment by puneet426** [comment]
@Rajan-Barnwal please level it

**Comment by puneet426** [comment]
@Rajan-Barnwal pleasemerge and close the isue

**Comment by puneet426** [comment]
hello @Rajan-Barnwal please merge this request

**Comment by puneet426** [comment]
hello @Rajan-Barnwal please merge this

**Pull request closed without merging**
